export const ChatList = [
    {
        chatId: 123,
        senderId: 1,
        senderName: "Alice",
        messagePreview: "Thank You ",
        unread: true,
        isOnline: false,
    },
    {
        chatId: 234,
        senderId: 2,
        senderName: "Charlie",
        messagePreview: "Thank You",
        unread: true,
        isOnline: true,
    },
    {
        chatId: 345,
        senderId: 3,
        senderName: "Bob",
        messagePreview: "What about you?",
        unread: false,
        isOnline: true,
    },
    // {
    //     chatId: 456,
    //     senderId: 4,
    //     senderName: "John Wick",
    //     messagePreview: "Thank You ",
    //     unread: true,
    //     isOnline: false,
    // },
    // {
    //     chatId: 567,
    //     senderId: 5,
    //     senderName: "Harry Potter",
    //     messagePreview: "Thank You",
    //     unread: true,
    //     isOnline: true,
    // },
    // {
    //     chatId: 678,
    //     senderId: 6,
    //     senderName: "Mohammad Awais",
    //     messagePreview: "What about you?",
    //     unread: false,
    //     isOnline: true,
    // },
    // {
    //     chatId: 789,
    //     senderId: 7,
    //     senderName: "John Wick",
    //     messagePreview: "Thank You ",
    //     unread: true,
    //     isOnline: false,
    // },
    // {
    //     chatId: 890,
    //     senderId: 8,
    //     senderName: "Harry Potter",
    //     messagePreview: "Thank You",
    //     unread: true,
    //     isOnline: true,
    // },
    // {
    //     chatId: 910,
    //     senderId: 9,
    //     senderName: "Mohammad Awais",
    //     messagePreview: "What about you?",
    //     unread: false,
    //     isOnline: true,
    // },
];
